import Anthropic from "@anthropic-ai/sdk";
import type { GeneratedItinerary, ItineraryDay, TripInput } from "./types";

const MODEL = process.env.ANTHROPIC_MODEL || "claude-opus-4-8";

// JSON schema handed to the model via structured outputs. Every property is
// required and additionalProperties is false — both mandated by the structured
// outputs feature. See shared/tool-use-concepts.md (structured outputs).
const ITINERARY_SCHEMA = {
  type: "object",
  additionalProperties: false,
  properties: {
    title: { type: "string" },
    summary: { type: "string" },
    days: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          day: { type: "integer" },
          date: { type: "string" },
          title: { type: "string" },
          activities: {
            type: "array",
            items: {
              type: "object",
              additionalProperties: false,
              properties: {
                time: { type: "string" },
                title: { type: "string" },
                description: { type: "string" },
                location: { type: "string" },
                category: { type: "string" },
                estimatedCost: { type: "string" },
              },
              required: [
                "time",
                "title",
                "description",
                "location",
                "category",
                "estimatedCost",
              ],
            },
          },
        },
        required: ["day", "date", "title", "activities"],
      },
    },
    tips: { type: "array", items: { type: "string" } },
  },
  required: ["title", "summary", "days", "tips"],
} as const;

function dayCount(startDate: string, endDate: string): number {
  const start = new Date(startDate);
  const end = new Date(endDate);
  const diff = Math.round(
    (end.getTime() - start.getTime()) / (1000 * 60 * 60 * 24),
  );
  return Math.max(1, diff + 1);
}

function isoDate(base: string, offsetDays: number): string {
  const d = new Date(base);
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString().slice(0, 10);
}

function buildPrompt(input: TripInput, days: number): string {
  const interests = input.interests.length
    ? input.interests.join(", ")
    : "a general mix of experiences";
  return [
    `Plan a ${days}-day travel itinerary for ${input.destination}.`,
    ``,
    `Trip details:`,
    `- Dates: ${input.startDate} to ${input.endDate} (${days} days)`,
    `- Travelers: ${input.travelers}`,
    input.budget ? `- Budget: ${input.budget}` : `- Budget: flexible`,
    `- Interests: ${interests}`,
    `- Pace: ${input.pace}`,
    input.notes ? `- Special requests: ${input.notes}` : ``,
    ``,
    `Produce a realistic, well-sequenced day-by-day plan. For each day give it a`,
    `short theme title and 3-5 activities with a time of day, a concrete place,`,
    `a one- to two-sentence description, a category, and a rough estimated cost.`,
    `Group activities geographically to minimize backtracking. Include a handful`,
    `of practical tips for the trip. Set each day's "date" field to the actual`,
    `calendar date for that day of the trip.`,
  ]
    .filter(Boolean)
    .join("\n");
}

// Deterministic fallback so the entire app runs end-to-end without an API key.
function mockItinerary(input: TripInput, days: number): GeneratedItinerary {
  const templates = [
    { time: "09:00", title: "Local breakfast", category: "Food", cost: "$15 pp" },
    {
      time: "11:00",
      title: "Landmark visit",
      category: "Sightseeing",
      cost: "$25 pp",
    },
    { time: "14:00", title: "Neighborhood walk", category: "Leisure", cost: "Free" },
    { time: "19:30", title: "Dinner out", category: "Food", cost: "$40 pp" },
  ];

  const itineraryDays: ItineraryDay[] = Array.from({ length: days }, (_, i) => ({
    day: i + 1,
    date: isoDate(input.startDate, i),
    title: `Day ${i + 1} in ${input.destination}`,
    activities: templates.map((t) => ({
      time: t.time,
      title: `${t.title}`,
      description: `A ${input.pace} ${t.category.toLowerCase()} experience in ${input.destination}.`,
      location: input.destination,
      category: t.category,
      estimatedCost: t.cost,
    })),
  }));

  return {
    title: `${days}-Day Trip to ${input.destination}`,
    summary: `A ${input.pace} ${days}-day plan for ${input.travelers} traveler(s) in ${input.destination}. (Generated by the built-in demo planner — set ANTHROPIC_API_KEY to enable AI generation.)`,
    days: itineraryDays,
    tips: [
      "Book popular attractions in advance to skip lines.",
      "Carry a small amount of local currency for markets.",
      "Keep a digital and paper copy of important documents.",
    ],
  };
}

/**
 * Generate a structured itinerary from trip inputs.
 * Uses the Anthropic API when ANTHROPIC_API_KEY is set, otherwise falls back
 * to a deterministic mock so the app is runnable out of the box.
 */
export async function generateItinerary(
  input: TripInput,
): Promise<GeneratedItinerary> {
  const days = dayCount(input.startDate, input.endDate);

  if (!process.env.ANTHROPIC_API_KEY) {
    return mockItinerary(input, days);
  }

  const client = new Anthropic();

  // output_config (structured outputs) is a current API parameter; some SDK
  // type versions don't yet expose it, so we assemble params loosely and type
  // the response explicitly.
  const params = {
    model: MODEL,
    max_tokens: 16000,
    system:
      "You are an expert travel agent who builds detailed, realistic, well-paced itineraries. Return only the structured itinerary — no preamble.",
    messages: [{ role: "user", content: buildPrompt(input, days) }],
    output_config: {
      format: { type: "json_schema", schema: ITINERARY_SCHEMA },
    },
  };

  const response = (await client.messages.create(
    params as unknown as Anthropic.MessageCreateParamsNonStreaming,
  )) as Anthropic.Message;

  const textBlock = response.content.find(
    (b): b is Anthropic.TextBlock => b.type === "text",
  );
  if (!textBlock) {
    throw new Error("Model returned no text content.");
  }

  const parsed = JSON.parse(textBlock.text) as GeneratedItinerary;
  return parsed;
}
